### ISSUE TITLE
Building new provider for Fabric Answers and Firebase

### ISSUE THREAD

**Issue by nikans** [Legoless/Analytical#1]
Hey Dal,
I'm pretty new to all those podspec and static libraries stuff, so I got bumped by the fact that I can't include Fabric module in my (your =) ) pod, even if the mentioned framework exists in the project. So I asked on SO, maybe you can help, too.
http://stackoverflow.com/questions/42472928/cannot-import-module-from-another-pod
I understood, you have the same issue with GA.
Thanks.

**Comment by nikans** [comment]
Bump )

**Comment by Legoless** [comment]
Well, Analytical does not support Fabric Answers and Firebase yet. Can you give me more information what are you trying to do exactly? @nikans

**Comment by Legoless** [comment]
Both Answers and Firebase are implemented as of 0.5.0.
